---
title: "BDA project sanity check"
author: "Markus Henttonen"
output:
  pdf_document: 
    toc: yes
    toc_depth: 1
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
test_arr <- read.csv(file=paste0('data\\clean\\weekly\\', 'PRSA_Data_Aotizhongxin_20130301-20170228.csv'))

```



```{r}
head(test_arr)
```

```{r}
t_series <- log(ts(test_arr$PM2.5, frequency = 52))
```


```{r}
ts.plot(t_series)
```



```{r}
acf(t_series, lag.max=105)
acf(t_series, lag.max=105, type = "partial")
```




```{r}
diffs <- diff(t_series, lag = 52, differences = 1)
ts.plot(diffs)
acf(diffs, lag.max=105)
acf(diffs, lag.max=105, type = "partial")
```


```{r}
diffn <- diff(t_series, lag = 1, differences = 1)
ts.plot(diffn)
acf(diffn, lag.max=105)
acf(diffn, lag.max=105, type = "partial")
```




```{r}
diffn <- diff(t_series, lag = 1, differences = 1)
diffsn <- diff(t_series, lag = 52, differences = 1)
ts.plot(diffsn)
acf(diffsn, lag.max=105)
acf(diffsn, lag.max=105, type = "partial")
```




