---
title: "Regression Test"
author: "Anselmi Jokinen"
date: "12/5/2021"
output: html_document
---

```{r, warning=FALSE}
library(rstan)
library(loo)

rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
```

# Load and format data

```{r}
# Maximum number of allowed data points
max_N <- 1000

# Amount of series used
M <- 6

# Initialize x and y
x <- matrix(rep(0, max_N), ncol=1)
y <- matrix(rep(0, max_N), ncol=1)

for (file in list.files(path="data/clean/monthly/")) {
  
  # Read file
  file_data <- read.csv(file=paste0("data/clean/monthly/", file))
  
  # Select desired data from file
  file_x <- file_data$O3
  file_y <- file_data$TEMP
  
  # Number of rows used is the min across all series
  nrows <- min(dim(x)[1], dim(y)[1], length(file_x), length(file_y))
  
  # Drop extra rows
  x <- x[1:nrows,]
  y <- y[1:nrows,]
  file_x <- file_x[1:nrows]
  file_y <- file_y[1:nrows]
  
  # Add column from file to the data
  x <- cbind(x, matrix(file_x, ncol=1))
  y <- cbind(y, matrix(file_y, ncol=1))
}

# Drop the columns created for initialization
ncols <- dim(x)[2]
x <- x[,2:ncols]
y <- y[,2:ncols]
```

# Plot data

```{r}
for (i in 1:M) {
  plot(x[,i], y[,i])
}
```

# Fit models

```{r, results='hide', include=FALSE}
stan_data <- list(
  x = x[,1:M],
  y = y[,1:M],
  N = dim(x)[1],
  M = M,
  x_pred = x[,1:M]
)

model_sep <- stan(file="separate_regression.stan", data=stan_data, iter=6000)

df_sep <- as.data.frame(model_sep)
```

```{r, results='hide', include=FALSE}
new_x <- runif(dim(x)[1], 0, 120)
stan_data <- list(
  x = x[,1:M],
  y = y[,1:M],
  N = dim(x)[1],
  M = M,
  x_pred = cbind(x[,1:M], new_x)
)

model_hier <- stan(
  file="hierarchial_regression.stan",
  data=stan_data,
  iter=6000,
  control = list(adapt_delta=0.99) # default 0.8
)

df_hier <- as.data.frame(model_hier)
```

# Trace plots

```{r}
pars1 = c()
for (i in 1:M) {
  pars1 = c(pars1, paste0("alpha[", i, "]"))
}
traceplot(model_hier, inc_warmup=FALSE, pars=pars1)
```

```{r}
pars2 = c()
for (i in 1:M) {
  pars2 = c(pars2, paste0("beta[", i, "]"))
}
traceplot(model_hier, inc_warmup=FALSE, pars=pars2)
```

# Convergence diagnostics

```{r, include=FALSE}
monitor_sep <- monitor(model_sep)
monitor_hier <- monitor(model_hier)
```

```{r}
print.data.frame(monitor_sep[1:(3*M),c("Rhat", "n_eff")])
print.data.frame(monitor_hier[1:(5+2*M),c("Rhat", "n_eff")])
```

# Loo

```{r}
loo_sep <- loo(model_sep, pars="log_lik")
loo_hier <- loo(model_hier, pars="log_lik")
loo_sep$estimates
plot(loo_sep)
loo_hier$estimates
plot(loo_hier)
```

# Posterior predictive check

```{r}
for (j in 1:M) {
  i <- sample(1:47, 1)
  choice <- paste0("y_pred[", i, ",", j, "]")
  draws <- unlist(df_sep[choice])
  hist(
    draws,
    breaks=20,
    main=paste0("Draws for x = ", round(x[i,j],2), " from series ", j),
    xlab = "y"
  )
  abline(v=y[i,j], col="red")
}
```

```{r}
for (j in 1:M) {
  i <- sample(1:47, 1)
  choice <- paste0("y_pred[", i, ",", j, "]")
  draws <- unlist(df_hier[choice])
  hist(
    draws,
    breaks=20,
    main=paste0("Draws for x = ", round(x[i,j],2), " from series ", j),
    xlab = "y"
  )
  abline(v=y[i,j], col="red")
}
```

```{r}
y_pred <- y
for (i in 1:dim(y)[1]) {
  for (j in 1:M) {
    choices <- df_sep[paste0("y_pred[", i, ",", j, "]")]
    k <- sample(1:12000, 1)
    y_pred[i,j] <- choices[k,]
  }
}

for (i in 1:M) {
  plot(x[,i], y[,i])
  points(x[,i], y_pred[,i], col="red")
}
```

```{r}
y_pred <- y
for (i in 1:dim(y)[1]) {
  for (j in 1:M+1) {
    choices <- df_hier[paste0("y_pred[", i, ",", j, "]")]
    k <- sample(1:12000, 1)
    y_pred[i,j] <- choices[k,]
  }
}

for (i in 1:M) {
  plot(x[,i], y_pred[,i], col="red")
  points(x[,i], y[,i])
}

plot(new_x, y_pred[,M+1], col="red")
points(x[,10], y[,10])
```

# Prior sensitivty analysis

```{r, results='hide', include=FALSE}
stan_data <- list(
  x = x[,1:M],
  y = y[,1:M],
  N = dim(x)[1],
  M = M,
  x_pred = x[,1:M]
)

model_sep2 <- stan(file="separate_regression2.stan", data=stan_data, iter=6000)

df_sep2 <- as.data.frame(model_sep2)
```

```{r}
for (i in 1:M) {
  first <- paste0("alpha[", i, "]")
  second <-paste0("beta[", i, "]")
  plot(unlist(df_sep[first]), unlist( df_sep[second]), xlab=first, ylab=second)
  plot(unlist(df_sep2[first]), unlist( df_sep2[second]), xlab=first, ylab=second, col="red")
}
```
